import os
import json
import zipfile
import shutil
import logging
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime

logger = logging.getLogger(__name__)

CLASSES = ["standing", "lying", "foaling"]


class ExportService:
    def __init__(self):
        self.exports_dir = Path("exports")
        self.uploads_dir = Path("uploads")
        self.exports_dir.mkdir(exist_ok=True)

    def export_dataset(self, project_data: Dict[str, Any]) -> str:
        """
        Generate a YOLO-format dataset ZIP from project annotations.
        Returns path to the ZIP file.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        export_name = f"horse_dataset_{timestamp}"
        export_dir = self.exports_dir / export_name

        # Create structure
        (export_dir / "images" / "train").mkdir(parents=True, exist_ok=True)
        (export_dir / "labels" / "train").mkdir(parents=True, exist_ok=True)

        images_list = project_data.get("images", [])
        exported_count = 0
        skipped_count = 0

        for img_data in images_list:
            image_id = img_data.get("id", "")
            filename = img_data.get("filename", "")
            annotations = img_data.get("annotations", [])

            if not filename:
                skipped_count += 1
                continue

            # Source image
            src_path = self.uploads_dir / filename
            if not src_path.exists():
                logger.warning(f"Image not found: {src_path}")
                skipped_count += 1
                continue

            # Destination
            stem = Path(filename).stem
            dst_image = export_dir / "images" / "train" / filename
            dst_label = export_dir / "labels" / "train" / f"{stem}.txt"

            # Copy image
            shutil.copy2(src_path, dst_image)

            # Write label file
            label_lines = []
            for ann in annotations:
                cls_id = ann.get("class_id", 0)
                cx = ann.get("cx", 0)
                cy = ann.get("cy", 0)
                bw = ann.get("bw", 0)
                bh = ann.get("bh", 0)

                # Clamp values
                cx = max(0.0, min(1.0, float(cx)))
                cy = max(0.0, min(1.0, float(cy)))
                bw = max(0.001, min(1.0, float(bw)))
                bh = max(0.001, min(1.0, float(bh)))

                label_lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")

            with open(dst_label, "w") as f:
                f.write("\n".join(label_lines))

            exported_count += 1

        # Write data.yaml
        yaml_content = self._generate_data_yaml(export_name, len(images_list))
        with open(export_dir / "data.yaml", "w") as f:
            f.write(yaml_content)

        # Write README
        readme_content = self._generate_readme(exported_count, project_data)
        with open(export_dir / "README.md", "w") as f:
            f.write(readme_content)

        # Write stats JSON
        stats = {
            "export_timestamp": timestamp,
            "total_images": len(images_list),
            "exported_images": exported_count,
            "skipped_images": skipped_count,
            "classes": CLASSES,
            "annotation_counts": self._count_annotations(images_list)
        }
        with open(export_dir / "stats.json", "w") as f:
            json.dump(stats, f, indent=2)

        # Create ZIP
        zip_path = self.exports_dir / f"{export_name}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in export_dir.rglob("*"):
                if file_path.is_file():
                    arcname = file_path.relative_to(self.exports_dir)
                    zf.write(file_path, arcname)

        # Cleanup temp dir
        shutil.rmtree(export_dir, ignore_errors=True)

        logger.info(f"✅ Exported {exported_count} images to {zip_path}")
        return str(zip_path)

    def _generate_data_yaml(self, export_name: str, num_images: int) -> str:
        classes_list = "\n".join([f"  {i}: {c}" for i, c in enumerate(CLASSES)])
        return f"""# Horse Dataset - Generated by Horse Annotator
# Export: {export_name}

path: .
train: images/train
val: images/train  # Update with validation split when available

nc: {len(CLASSES)}
names:
{classes_list}

# Class descriptions:
# 0: standing - Horse standing upright
# 1: lying    - Horse lying down
# 2: foaling  - Mare giving birth / foal being born
"""

    def _generate_readme(self, exported_count: int, project_data: Dict) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        project_name = project_data.get("name", "Horse Dataset")
        return f"""# {project_name}

Generated by **Horse Annotator** - YOLO Dataset Annotation Tool
Export Date: {timestamp}
Total Annotated Images: {exported_count}

## Structure

```
dataset/
├── images/
│   └── train/       # Training images
├── labels/
│   └── train/       # YOLO format label files
├── data.yaml        # Dataset configuration
└── stats.json       # Export statistics
```

## Label Format

YOLO format: `class_id center_x center_y width height`
All values normalized to [0, 1].

## Classes

| ID | Name     | Description                    |
|----|----------|--------------------------------|
| 0  | standing | Horse standing upright         |
| 1  | lying    | Horse lying down               |
| 2  | foaling  | Mare giving birth / foal       |

## Training Example (YOLOv8)

```bash
pip install ultralytics
yolo train model=yolov8n.pt data=data.yaml epochs=100 imgsz=640
```

## Notes

- Images are in original resolution
- Bounding boxes manually verified/annotated
- Auto-detected with YOLOv8 pretrained model
"""

    def _count_annotations(self, images_list: List) -> Dict:
        counts = {c: 0 for c in CLASSES}
        total = 0
        for img in images_list:
            for ann in img.get("annotations", []):
                cls_id = ann.get("class_id", 0)
                if 0 <= cls_id < len(CLASSES):
                    counts[CLASSES[cls_id]] += 1
                total += 1
        counts["total"] = total
        return counts


export_service = ExportService()
